name: codecov generate
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-18.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.3.1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 14

      # - name: yarn install from npmjs registry
      #   run: |
      #     yarn install --no-lockfile
      #     yarn install-client:nolockfile

      - name: Configure private AWS npm registry and install packages from it
        # if: ${{ failure() }}
        run: |
          npm config set registry https://packages.deskreen.com/
          npm set //packages.deskreen.com/:_authToken="${{ secrets.NPMRC_USER_TOKEN }}"
          npm config set always-auth true
          yarn install --frozen-lockfile
          yarn install-client:frozenlockfile

      - name: yarn build
        run: yarn build

      - name: yarn test
        run: yarn test

      - name: yarn coverage
        run: yarn coverage

      - name: Upload app coverage to Codecov
        uses: codecov/codecov-action@v1.0.12
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/clover.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

      - name: Upload app/client coverage to Codecov
        uses: codecov/codecov-action@v1.0.12
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./app/client/coverage/clover.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
